config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :artists do
    resources :songs, only: [:create]
  end
  resources :songs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: {maximum: 500}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end


  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      require.params(:artist).permit(:name, :image)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:destroy]
  before_action :set_artist, only: [:create]

  def create

    @song = @artist.songs.create(song_params)
    redirect_to @artist
  end

  def destroy
    artist = @song.artist
    @song.destroy
    redirect_to artist
  end

  private
    def song_params
      params.require(:song).permit(:name)
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_formsong.html.erb
<%= form_for [@artist, @artist.songs.new] do |f| %>
  <p><strong>Add a new song</strong>
    <label>Song title:</label>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "add song", class: "btn btn-success" %>
  </div>
<% end %>

app/views/artists/index.html.erb
<h1>All artists</h1>
<hr>

<% @artists.each do |artist| %>
  <%= image_tag artist.image.icon %>
  <h3><%= link_to artist.name, artist_path(artist.id) %></h3>
  <%= button_to "delete artist", {action: 'destroy', id: artist.id }, method: :delete, data: {confirm: "Are you sure you want to delete #{artist.name}?"}
 %>
 <hr>
<% end %>

app/views/artists/show.html.erb
<h1>Songs by <%= @artist.name %>:</h1>
<ul>
  <% @artist.songs.each do |song| %>
  <li><%= song.name %> <%= button_to "delete song", {controller: :songs, action: 'destroy', id: song.id }, method: :delete, data: {confirm: "Are you sure you want to delete #{song.name}?"}, class: 'deletebtn'
 %></li>
<% end %>
</ul>
<hr>
<div>
  <%= render 'formsong' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<div>
  <%= link_to "home", root_path %>
</div>

app/views/shared/_formsong.html.erb
<%= form_for [@artist, @artist.songs.new] do |f| %>
  <p><strong>Add a new song</strong>
    <label>Song title:</label>
    <%= f.text_field :name %>
  </div>

  <hr>

  <div class="actions">
    <%= f.submit "add song", class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div>
  <%= link_to "home", root_path %>
</div>